"""Build a standalone Python file that turns one SAE feature into an
image classifier.

The generated script:

  - downloads the SAE checkpoint from the Hugging Face dataset repo
  - loads the matching vision backbone (DINOv2 / DINOv3 / CLIP) on
    whatever device is available
  - exposes ``make_classifier()``, returning a callable that takes an
    image (path or PIL) and returns ``{"score": float, "fires": bool}``
  - has a ``__main__`` so it runs end-to-end with **no arguments** — it
    downloads the explorer's image tarball and scores the feature's own
    top-activating image (which is guaranteed to fire), or you can pass
    ``python sae_classifier_*.py your_image.jpg [--threshold T] [--agg max|mean]``

Default threshold is baked in at export time (half the feature's peak
observed activation, suitable for the default ``max`` aggregation —
image fires if any patch fires strongly).
"""

import re
from typing import Optional


_TEMPLATE = '''"""Standalone SAE feature classifier — feature %%FEAT%% from %%LABEL%%.

Auto-generated by the SAE Feature Explorer. Loads %%BACKBONE%% layer
%%LAYER%% (%%TOKEN_TYPE%% tokens) and the %%SAE_FILE%% SAE checkpoint,
then for any input image returns the activation of feature %%FEAT%%
as a classification score. Apply ``--threshold`` to get a boolean
fires/doesn't-fire decision.

Setup (one-time):

    pip install torch torchvision transformers huggingface_hub Overcomplete Pillow

Usage:

    # No arguments — downloads the demo image tarball and scores this
    # feature's own top-activating image (a guaranteed positive):
    python %%FILENAME%%

    # Or score your own image:
    python %%FILENAME%% path/to/image.jpg
    python %%FILENAME%% path/to/image.jpg --threshold 0.5 --agg mean

    # or from Python:
    from %%MODULE%% import make_classifier
    cls = make_classifier()
    result = cls("path/to/image.jpg")
    # -> {"score": 0.42, "fires": True}
"""
from __future__ import annotations

import argparse
import tarfile
import tempfile
from typing import Union

import torch
from PIL import Image
from torchvision import transforms as trn
from huggingface_hub import hf_hub_download

# ---------- Config baked in at export time ----------
FEAT              = %%FEAT%%
BACKBONE          = "%%BACKBONE%%"
LAYER             = %%LAYER%%
TOKEN_TYPE        = "%%TOKEN_TYPE%%"
SAE_REPO          = "%%SAE_REPO%%"
SAE_FILE          = "%%SAE_FILE%%"
D_SAE             = %%D_SAE%%
TOP_K             = %%TOP_K%%
DEFAULT_THRESHOLD = %%DEFAULT_THRESHOLD%%

# Toy data: the explorer's image tarball + this feature's top-activating
# image inside it. Used when the script is run with no image argument.
IMAGES_REPO       = "%%IMAGES_REPO%%"
IMAGES_TARBALL    = "%%IMAGES_TARBALL%%"
TOP_IMAGE         = "%%TOP_IMAGE%%"

_DINO_MEAN = [0.485, 0.456, 0.406]
_DINO_STD  = [0.229, 0.224, 0.225]


def _dino_transform(image_size: int):
    return trn.Compose([
        trn.Resize((image_size, image_size),
                   interpolation=trn.InterpolationMode.BICUBIC,
                   antialias=True),
        trn.ToTensor(),
        trn.Normalize(_DINO_MEAN, _DINO_STD),
    ])


def _load_backbone(device):
    """Return (forward_fn, transform_fn, d_hidden, n_reg) for the
    configured backbone. ``forward_fn`` takes a (1, C, H, W) tensor on
    ``device`` and returns the per-token hidden state."""
    if BACKBONE == "clip":
        from transformers import CLIPModel, CLIPImageProcessor
        model = CLIPModel.from_pretrained(
            "openai/clip-vit-large-patch14", torch_dtype=torch.float32,
        ).to(device).eval()
        proc = CLIPImageProcessor.from_pretrained("openai/clip-vit-large-patch14")
        d_hidden = model.config.vision_config.hidden_size
        n_reg    = 0
        def transform_fn(pil):
            return proc(images=pil, return_tensors="pt")["pixel_values"].squeeze(0)
        if LAYER is not None:
            _embed   = model.vision_model.embeddings
            _prenorm = model.vision_model.pre_layrnorm
            _layers  = model.vision_model.encoder.layers
            def forward_fn(t):
                h = _embed(t)
                h = _prenorm(h)
                for i, ly in enumerate(_layers):
                    out = ly(hidden_states=h, attention_mask=None,
                             causal_attention_mask=None)
                    h = out[0] if isinstance(out, (tuple, list)) else out
                    if i == LAYER - 1:
                        return h
                return h
        else:
            def forward_fn(t):
                return model.vision_model(pixel_values=t).last_hidden_state
        return forward_fn, transform_fn, d_hidden, n_reg

    if BACKBONE.startswith("dinov2"):
        model = torch.hub.load(
            "facebookresearch/dinov2", "dinov2_vitb14"
        ).to(device).eval()
        d_hidden = 768
        n_reg    = 0
        _xfm = _dino_transform(224)
        def transform_fn(pil):
            return _xfm(pil)
        if LAYER is not None:
            _act = [None]
            def _hook(_m, _i, out):
                _act[0] = out
            model.blocks[LAYER].register_forward_hook(_hook)
            def forward_fn(t):
                _act[0] = None
                model.forward_features(t)
                return _act[0]
        else:
            def forward_fn(t):
                out = model.forward_features(t)
                return torch.cat(
                    [out["x_norm_clstoken"].unsqueeze(1), out["x_norm_patchtokens"]],
                    dim=1,
                )
        return forward_fn, transform_fn, d_hidden, n_reg

    # dinov3
    from transformers import AutoModel
    model = AutoModel.from_pretrained(
        "facebook/dinov3-vitl16-pretrain-lvd1689m", dtype=torch.float32,
    ).to(device).eval()
    d_hidden = model.config.hidden_size
    n_reg    = model.config.num_register_tokens
    _xfm = _dino_transform(256)
    def transform_fn(pil):
        return _xfm(pil)
    use_intermediate = LAYER is not None
    def forward_fn(t):
        out = model(pixel_values=t, output_hidden_states=use_intermediate)
        return out.hidden_states[LAYER] if use_intermediate else out.last_hidden_state
    return forward_fn, transform_fn, d_hidden, n_reg


def _extract_patch_tokens(hidden, n_reg):
    if TOKEN_TYPE == "cls":
        return hidden[:, 0:1, :]
    if BACKBONE == "clip" or BACKBONE.startswith("dinov2"):
        return hidden[:, 1:, :]
    return hidden[:, 1 + n_reg:, :]


def _load_sae(device, d_hidden):
    from overcomplete.sae import TopKSAE
    print(f"[sae-classifier] downloading {SAE_FILE} from {SAE_REPO} ...")
    local = hf_hub_download(
        repo_id=SAE_REPO, filename=SAE_FILE, repo_type="dataset",
    )
    sae = TopKSAE(
        input_shape=d_hidden, nb_concepts=D_SAE,
        top_k=TOP_K, device=device,
    )
    sae.load_state_dict(torch.load(local, map_location=device, weights_only=True))
    sae.eval()
    return sae


def _download_toy_image():
    """Download the explorer image tarball and extract this feature's
    top-activating image (a guaranteed positive). Returns a local path."""
    if not IMAGES_REPO or not IMAGES_TARBALL or not TOP_IMAGE:
        raise SystemExit(
            "No toy data baked into this export; pass an image path: "
            "python %%FILENAME%% path/to/image.jpg"
        )
    print(f"[sae-classifier] downloading {IMAGES_TARBALL} from {IMAGES_REPO} ...")
    tar_path = hf_hub_download(
        repo_id=IMAGES_REPO, filename=IMAGES_TARBALL, repo_type="dataset",
    )
    out_dir = tempfile.mkdtemp(prefix="sae_toy_")
    with tarfile.open(tar_path) as tf:
        member = next(
            (m for m in tf.getmembers()
             if m.isfile() and m.name.rsplit("/", 1)[-1] == TOP_IMAGE),
            None,
        )
        if member is None:
            raise SystemExit(
                f"{TOP_IMAGE!r} not found in {IMAGES_TARBALL}; "
                "pass your own image path instead."
            )
        tf.extract(member, out_dir)
        import os
        return os.path.join(out_dir, member.name)


def make_classifier(device: Union[torch.device, str, None] = None,
                    agg: str = "max"):
    """Return a ``classify(image, threshold)`` callable.

    ``agg`` reduces the per-patch activations to a single image-level
    score: ``"max"`` (default — image fires if any patch fires strongly),
    ``"mean"`` (average response across patches), or ``"sum"``.
    """
    if device is None:
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    elif isinstance(device, str):
        device = torch.device(device)
    if agg not in {"max", "mean", "sum"}:
        raise ValueError(f"agg must be max|mean|sum, got {agg!r}")

    forward_fn, transform_fn, d_hidden, n_reg = _load_backbone(device)
    sae = _load_sae(device, d_hidden)

    def classify(image, threshold: float = DEFAULT_THRESHOLD):
        if isinstance(image, str):
            pil = Image.open(image).convert("RGB")
        else:
            pil = image if image.mode == "RGB" else image.convert("RGB")
        with torch.no_grad():
            t = transform_fn(pil).unsqueeze(0).to(device)
            hidden = forward_fn(t)
            tokens = _extract_patch_tokens(hidden, n_reg)
            flat = tokens.reshape(-1, d_hidden)
            _, z, _ = sae(flat)                                # (n_patches, d_sae)
            patch_acts = z[:, FEAT].float()
            if agg == "max":
                score = patch_acts.max().item()
            elif agg == "mean":
                score = patch_acts.mean().item()
            else:
                score = patch_acts.sum().item()
        return {"score": float(score), "fires": float(score) > float(threshold)}

    return classify


if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description=f"Classifier for SAE feature {FEAT} ({BACKBONE} layer {LAYER}).",
    )
    parser.add_argument(
        "image", nargs="?", default=None,
        help="Path to an input image. If omitted, downloads the demo image "
             "tarball and scores this feature's top-activating image.",
    )
    parser.add_argument(
        "--threshold", type=float, default=DEFAULT_THRESHOLD,
        help=f"Activation threshold for fires/doesn't-fire (default: {DEFAULT_THRESHOLD}).",
    )
    parser.add_argument(
        "--agg", choices=["max", "mean", "sum"], default="max",
        help="How to reduce per-patch activations to a single score (default: max).",
    )
    parser.add_argument(
        "--device", default=None,
        help="torch device override (default: cuda if available, else cpu).",
    )
    cli = parser.parse_args()
    image = cli.image if cli.image is not None else _download_toy_image()
    cls = make_classifier(device=cli.device, agg=cli.agg)
    result = cls(image, threshold=cli.threshold)
    print(
        f"feat {FEAT}: score={result['score']:.4f}  "
        f"fires={result['fires']}  (threshold={cli.threshold}, agg={cli.agg})  "
        f"image={image}"
    )
'''


_SUBSTITUTIONS = (
    "FEAT", "LABEL", "BACKBONE", "LAYER", "TOKEN_TYPE",
    "SAE_REPO", "SAE_FILE", "D_SAE", "TOP_K",
    "DEFAULT_THRESHOLD", "FILENAME", "MODULE",
    "IMAGES_REPO", "IMAGES_TARBALL", "TOP_IMAGE",
)


def _parse_top_k_from_filename(sae_file: str) -> Optional[int]:
    """Mirror of src/precompute_utils.parse_top_k_from_path, with no
    sys.path acrobatics so the explorer can call it directly."""
    m = re.search(r"_k(\d+)[_.]", sae_file)
    return int(m.group(1)) if m else None


def build_classifier_script(
    feat: int,
    ds: dict,
    hf_data_repo: str,
    default_threshold: float,
    top_image_basename: str = "",
    hf_images_repo: str = "",
    images_tarball: str = "",
) -> tuple[str, str]:
    """Return ``(script_text, filename)`` for the active dataset's
    classifier export at ``feat``.

    Pulls everything from ``ds`` and the registry:
      - ``ds['backbone']``, ``ds['layer']``, ``ds['token_type']``
      - ``ds['sae_file']``, ``ds['d_model']``
      - ``hf_data_repo`` to construct the SAE download URL
      - ``default_threshold`` is baked in as the script's
        ``DEFAULT_THRESHOLD`` (typically half the feature's peak
        activation; see the explorer's export button).
      - ``top_image_basename`` / ``hf_images_repo`` / ``images_tarball``
        let the generated script fetch the demo image tarball and score
        this feature's top-activating image with no arguments. When any
        is empty, the script requires an explicit image path.
    """
    sae_file = ds.get("sae_file") or ""
    top_k = _parse_top_k_from_filename(sae_file)
    if top_k is None:
        raise ValueError(
            f"could not parse top_k from sae_file={sae_file!r}; "
            "filenames must look like '..._k160_...'."
        )
    filename = f"sae_classifier_feat{feat}.py"
    module   = filename[:-3]
    values = {
        "FEAT":              str(int(feat)),
        "LABEL":             str(ds.get("label", "")),
        "BACKBONE":          str(ds.get("backbone", "dinov3")),
        "LAYER":             "None" if ds.get("layer") is None else str(int(ds["layer"])),
        "TOKEN_TYPE":        str(ds.get("token_type", "spatial")),
        "SAE_REPO":          str(hf_data_repo or ""),
        "SAE_FILE":          str(sae_file),
        "D_SAE":             str(int(ds["d_model"])),
        "TOP_K":             str(int(top_k)),
        "DEFAULT_THRESHOLD": f"{float(default_threshold):.6f}",
        "FILENAME":          filename,
        "MODULE":            module,
        "IMAGES_REPO":       str(hf_images_repo or ""),
        "IMAGES_TARBALL":    str(images_tarball or ""),
        "TOP_IMAGE":         str(top_image_basename or ""),
    }
    out = _TEMPLATE
    for key in _SUBSTITUTIONS:
        out = out.replace(f"%%{key}%%", values[key])
    return out, filename
